project_id = "mcszrtlpbsesanylyzmi"

[functions.yookassa-payment]
verify_jwt = false

[functions.paymaster-payment]
verify_jwt = false

[functions.nspk-webhook]
verify_jwt = false

[functions.paymaster-webhook]
verify_jwt = false