// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcszrtlpbsesanylyzmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jc3pydGxwYnNlc2FueWx5em1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjUyNzEsImV4cCI6MjA2NjAwMTI3MX0.rdjhbhIq9yXm2AaPdwBEEhDKBjJfHIZZX7vwT7eL53M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});